# -*- coding: utf-8 -*-
countries = {'East Timor': 'au Timor oriental',
             'Canada': 'au Canada',
             'Italy': 'en Italie',
             'Bangladesh': 'au Bangladesh',
             'Bhutan': 'au Bhoutan',
             'Panama': 'au Panama',
             'Nepal': 'au Népal',
             'india': 'en Inde',
             'Costa Rica': 'au Costa Rica',
             'Mongolia': 'en Mongolie',
             'France': 'en France',
             'Luxembourg': 'au Luxembourg',
             'Sri Lanka': 'au Sri Lanka',
             'Peru': 'au Pérou',
             'Laos': 'au Laos',
             'Argentina': 'en Argentine',
             'Bolivia': 'en Bolivie',
             'Norway': 'en Norvège',
             'Maldova': 'en Moldavie',
             'Czech Republic': 'en République tchèque',
             'Guatamala': 'au Guatamala',
             'Brunei': 'au Brunei',
             'Belarus': 'en Bélarus',
             'Columbia': 'en Colombie',
             'Indonesia': 'en Indonésie',
             'Singapore': 'à Singapour',
             'Afganistan': 'en Afganistan',
             'Venezuela': 'au Venezuela',
             'Malaysia': 'en Malaisie',
             'Burma/Myanmar': 'en Birmanie',
             'Belgium': 'en Belgique',
             'Slovenia': 'en Slovénie',
             'China': 'en Chine',
             'Chile': 'au Chili',
             'Russian Federation': 'en Russie',
             'Russia': 'en Russie',
             'Thailand': 'en Thaïlande',
             'Netherlands (Holland)': 'aux Pays-Bas',
             'Belize': 'à Bélize',
             'Kazakhstan': 'au Kasakhastan',
             'Philippines': 'aux Philippines',
             'Spain': 'en Espagne',
             'Ukraine': 'en Ukraine',
             'Kyrgyzstan': 'au Kirghizistan',
             'Maldives': 'aux Maldives',
             'French Guyana': 'en Guyane française',
             'Denmark': 'au Danemark',
             'Turkey': 'en Turquie',
             'Finland': 'en Finlande',
             'Turkmenistan': 'au Turkmenistan',
             'Macedonia': 'en Macédonie',
             'United States': 'aux Etats-Unis',
             'Equador': 'en Equateur',
             'Sweden': 'en Suiède',
             'Vietnam': 'au Vietnam',
             'Croatia': 'en Croatie',
             'Cambodia': 'au Cambodge',
             'Guyana': 'en Guyane',
             'Switzerland': 'en Suisse',
             'Brazil': 'au Brésil',
             'Bulgaria': 'en Bulgarie',
             'Pakistan': 'au Pakistan',
             'Romania': 'en Roumanie',
             'Albania': 'en Albanie',
             'Honduras': 'au Honduras',
             'Portugal': 'au Portugal',
             'Suriname': 'au Surinam',
             'Uruguay': 'en Uruguay',
             'Nicaragua': 'au Nicaragua',
             'Mexico': 'au Mexique',
             'Liechtenstein': 'au Liechtenstein',
             'Uzbekistan': 'en Ouzbékistan',
             'El Salvador': 'au Salvador',
             'Austria': 'en Autriche',
             'Germany': 'en Allemagne',
             'Greece': 'en Grèce',
             'Paraguay': 'au Paraguay',
             'Japan': 'au Japon',
             'South Korea': 'en Corée du Sud',
             'Tajikistan': 'au Tadjikistan'}
